language: android
dist: trusty
jdk: oraclejdk11

env:
  global:

    - SLAVE_AAPT_TIMEOUT=31
    - TERM=dumb
    - GRADLE_OPTS="-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m  -Dfile.encoding=UTF-8"

matrix:
  fast_finish: true

android:
  components:

    - platform-tools
    - tools
    - build-tools-31.0.0
    - android-31
    - extra-google-m2repository
    - extra-android-m2repository

  # https://docs.travis-ci.com/user/languages/android/
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - git submodule update --init --recursive
  - chmod u+x gradlew
#  - android list sdk --no-ui --all --extended
#  - android list targets
#  - wget -r -nH -nd -np -R index.html* robots.txt* http://download.kiwix.org/dev/android/api/licenses/ -e robots=off -P $ANDROID_HOME/licenses || true
#  - yes | sdkmanager "platforms;android-29"

install: true

script:
  - ./gradlew -v
  - ./gradlew clean build --stacktrace

after_failure: true

notifications:
  email: false